Mongo:
  #  URL: "mongodb://duobei:RZmongo4cPRqq5@172.20.2.44:27017/datacenter?maxPoolSize=2000"
  URL: "mongodb://127.0.0.1:27017/?maxPoolSize=2000"
#MongoURL: "mongodb://report:3270815cb@dds-2ze494fdab7efbe4153t4-pub.mongodb.rds.aliyuncs.com:3717/duobei"

Kafka:
  Addr: [ "123.57.82.220:31090", "123.57.82.220:31091", "123.57.82.220:31092" ]
  #  Addr: ["127.0.0.1:9092"]
  Ver: "2.0.1"
  Topics: [
    #      "collect",
      "^paas-collect-.*", "^tosee-collect-.*",
    #      "^paas.*"
  ]
  GroupId: "inter-consumer3"
  Offset: "earliest"

Statsd:
  host: "60.205.144.70"
  port: 8135
  prefix: datacenter_statistics
